# Generated by Django 5.1.4 on 2024-12-06 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('bio', models.TextField()),
                ('content_category', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='creator_profiles/')),
                ('header_picture', models.ImageField(blank=True, null=True, upload_to='creator_profiles/')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='creator_profiles/')),
                ('youtube_subscribers', models.IntegerField(default=0)),
                ('instagram_followers', models.IntegerField(default=0)),
                ('tiktok_followers', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
