# Generated by Django 5.1.4 on 2024-12-06 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediakit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('contact_cta_text', models.CharField(default='Want to inquire about something a little different?', max_length=200)),
                ('contact_cta_button', models.CharField(default='Contact', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('media_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='mediakit.mediakit')),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('media_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='mediakit.mediakit')),
            ],
        ),
        migrations.CreateModel(
            name='ContentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.CharField(max_length=50)),
                ('media_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_stats', to='mediakit.mediakit')),
            ],
        ),
        migrations.CreateModel(
            name='SocialStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('stat_name', models.CharField(max_length=100)),
                ('stat_value', models.CharField(max_length=50)),
                ('media_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_stats', to='mediakit.mediakit')),
            ],
        ),
        migrations.AddField(
            model_name='mediakit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mediakit.tag'),
        ),
        migrations.CreateModel(
            name='WorkWithMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('service_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cta_button', models.CharField(default='Book now', max_length=50)),
                ('media_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_with_me', to='mediakit.mediakit')),
            ],
        ),
    ]
