# Generated by Django 5.1.4 on 2024-12-07 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediakit', '0002_mediakit_tag_gallery_demographic_contentstat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialStats',
            new_name='SocialStat',
        ),
        migrations.RemoveField(
            model_name='demographic',
            name='media_kit',
        ),
        migrations.RemoveField(
            model_name='mediakit',
            name='contact_cta_button',
        ),
        migrations.RemoveField(
            model_name='mediakit',
            name='contact_cta_text',
        ),
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('percentage', models.FloatField()),
                ('media_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_groups', to='mediakit.mediakit')),
            ],
        ),
        migrations.CreateModel(
            name='BrandPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
                ('media_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_partners', to='mediakit.mediakit')),
            ],
        ),
        migrations.DeleteModel(
            name='ContentStat',
        ),
        migrations.DeleteModel(
            name='Demographic',
        ),
    ]
