# Generated by Django 5.1.4 on 2024-12-07 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediakit', '0003_rename_socialstats_socialstat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_bracket', models.CharField(max_length=100)),
                ('age_stat_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CountryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_stat_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GenderStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_category', models.CharField(max_length=100)),
                ('gender_stat_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='socialstat',
            name='icon',
        ),
        migrations.AddField(
            model_name='brandpartner',
            name='integration_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='example_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workwithme',
            name='length_of_deliverables',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='workwithme',
            name='number_of_deliverables',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PlatformStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('subscribers', models.IntegerField()),
                ('engagement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_views', models.DecimalField(decimal_places=2, max_digits=10)),
                ('media_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_stats', to='mediakit.mediakit')),
            ],
        ),
        migrations.CreateModel(
            name='AudienceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_stats', models.ManyToManyField(blank=True, to='mediakit.agestats')),
                ('country_stats', models.ManyToManyField(blank=True, to='mediakit.countrystats')),
                ('gender_stats', models.ManyToManyField(blank=True, to='mediakit.genderstats')),
                ('platform_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_stats', to='mediakit.platformstats')),
            ],
        ),
        migrations.DeleteModel(
            name='AgeGroup',
        ),
        migrations.DeleteModel(
            name='CreatorProfile',
        ),
    ]
