# Generated by Django 5.1.4 on 2024-12-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediakit', '0004_agestats_countrystats_genderstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workwithme',
            name='offering',
            field=models.CharField(default='Short Form Video', max_length=150),
            preserve_default=False,
        ),
    ]
