# Generated by Django 5.1.4 on 2024-12-07 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediakit', '0005_workwithme_offering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiencestats',
            name='age_stats',
        ),
        migrations.RemoveField(
            model_name='audiencestats',
            name='country_stats',
        ),
        migrations.RemoveField(
            model_name='audiencestats',
            name='gender_stats',
        ),
        migrations.RemoveField(
            model_name='audiencestats',
            name='platform_stats',
        ),
        migrations.RemoveField(
            model_name='platformstats',
            name='media_kit',
        ),
        migrations.RemoveField(
            model_name='socialstat',
            name='media_kit',
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('twitch', 'Twitch'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('other', 'Other')], max_length=50)),
                ('followers', models.IntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('average_views', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('male_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('female_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('age_13_17_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('age_18_24_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('age_25_34_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('age_35_44_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('age_45_plus_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('top_country_1', models.CharField(blank=True, max_length=100, null=True)),
                ('top_country_1_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('top_country_2', models.CharField(blank=True, max_length=100, null=True)),
                ('top_country_2_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('top_country_3', models.CharField(blank=True, max_length=100, null=True)),
                ('top_country_3_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('media_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_platforms', to='mediakit.mediakit')),
            ],
        ),
        migrations.DeleteModel(
            name='AgeStats',
        ),
        migrations.DeleteModel(
            name='CountryStats',
        ),
        migrations.DeleteModel(
            name='GenderStats',
        ),
        migrations.DeleteModel(
            name='AudienceStats',
        ),
        migrations.DeleteModel(
            name='PlatformStats',
        ),
        migrations.DeleteModel(
            name='SocialStat',
        ),
    ]
