# Generated by Django 5.1.4 on 2024-12-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediakit', '0006_remove_audiencestats_age_stats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediakit',
            old_name='background_image',
            new_name='banner_image',
        ),
    ]
