# Generated by Django 5.1.4 on 2024-12-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediakit', '0012_gallery_video_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediakit',
            name='url_slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
