# Generated by Django 5.1.4 on 2024-12-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediakit', '0014_mediakit_show_offering_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediakit',
            name='show_public',
            field=models.BooleanField(default=True),
        ),
    ]
