# Generated by Django 5.1.4 on 2024-12-14 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediakit', '0015_mediakit_show_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediakit',
            name='url_slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_url_slug', message='URL slug must contain only lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')]),
        ),
    ]
